### ISSUE TITLE
panic when getting 410 from youtube

### ISSUE THREAD

**Issue by dolanor** [JackMordaunt/giffer#1]
Hi,
I wanted to try out giffer, but I got 
```
2021/09/12 01:14:55 error: fetching gif: downloading video: getting video: unexpected status code: 410
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7721d6]

goroutine 52 [running]:
main.(*UI).Update.func2(0xc0001c4000, 0xc00032c000, 0x2b, 0x4024000000000000, 0x402a000000000000, 0x4028000000000000, 0x190, 0x15e, 0x0)
	/home/dolanor/go/src/github.com/jackmordaunt/giffer/cmd/gio/main.go:162 +0x136
created by main.(*UI).Update
	/home/dolanor/go/src/github.com/jackmordaunt/giffer/cmd/gio/main.go:149 +0x3ac
exit status 2
```
Of course, I just watched the video on a browser.
Is it some change in the way youtube handle the video loading?

**Comment by JackMordaunt** [comment]
Yes, I believe YouTube has changed some things.
